import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					rel='shortcut icon'
					type='image/x-icon'
					href='favicon.ico'
				/>
				<link
					href='https://fonts.googleapis.com/css?family=Press+Start+2P&display=swap'
					rel='stylesheet'
				/>
				<link
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
					rel='stylesheet'
				/>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
